@backend_HostAddress = http://localhost:5292

POST {{backend_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "test123@gmail.com",
    "password": "123456"
}
###

POST {{backend_HostAddress}}/auth/signup
Content-Type: application/json

{
    "email": "Test123@gmail.com",
    "password": "123456",
    "fullname": "Huynh Ngoc Nhon"
}

###
GET http://localhost:5292/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNxZTFKZDZWa3lDMVZvTDEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2JmdmpwcXdieHhwaWFydnVtYmRqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlODFiMWEwYS01YzM3LTQzNmUtOWI4OS04YTc0NzJkY2JkNDMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYyNzk2OTA3LCJpYXQiOjE3NjI3OTMzMDcsImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiSHV5bmggTmdvYyBOaG9uIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJlODFiMWEwYS01YzM3LTQzNmUtOWI4OS04YTc0NzJkY2JkNDMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2Mjc5MzMwN31dLCJzZXNzaW9uX2lkIjoiYzljMTliMjItYTFkMi00ODdiLWEzMWYtYzVmMDA2YjJmOGZiIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.ODjDleyDmQrW3af8EX32M-PIFFd9F-irc0ySVWOPSHk
